language: ruby

rvm:  
  - 2.5
  - 2.6

before_install:
  - gem install bundler
  - gem update bundler
  - gem install alexandrite_base

script:
  - bundle exec rspec

notifications:
  email:
    recipients:
      - juan@daiuk.com.mx
    on_failure: change
    on_success: never
